/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      fontSize: {
        "display-lg": ["26px", { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["15px", { lineHeight: "22px" }],
        "body-md": ["14px", { lineHeight: "20px" }],
        "body-base": ["13px", { lineHeight: "18px" }],
        "body-sm": ["12px", { lineHeight: "16px" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "500" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-caps": ["10px", { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
      colors: {
        primary: "rgb(var(--color-primary-rgb) / <alpha-value>)",
        "on-primary": "rgb(var(--color-on-primary-rgb) / <alpha-value>)",
        "primary-container": "rgb(var(--color-primary-container-rgb) / <alpha-value>)",
        "on-primary-container": "rgb(var(--color-on-primary-container-rgb) / <alpha-value>)",
        secondary: "rgb(var(--color-secondary-rgb) / <alpha-value>)",
        "secondary-container": "rgb(var(--color-secondary-container-rgb) / <alpha-value>)",
        "on-secondary-container": "rgb(var(--color-on-secondary-container-rgb) / <alpha-value>)",
        surface: "rgb(var(--color-surface-rgb) / <alpha-value>)",
        "on-surface": "rgb(var(--color-on-surface-rgb) / <alpha-value>)",
        "surface-variant": "rgb(var(--color-surface-variant-rgb) / <alpha-value>)",
        "on-surface-variant": "rgb(var(--color-on-surface-variant-rgb) / <alpha-value>)",
        "surface-container-lowest": "rgb(var(--color-surface-container-lowest-rgb) / <alpha-value>)",
        "surface-container-low": "rgb(var(--color-surface-container-low-rgb) / <alpha-value>)",
        "surface-container": "rgb(var(--color-surface-container-rgb) / <alpha-value>)",
        "surface-container-high": "rgb(var(--color-surface-container-high-rgb) / <alpha-value>)",
        background: "rgb(var(--color-background-rgb) / <alpha-value>)",
        "on-background": "rgb(var(--color-on-background-rgb) / <alpha-value>)",
        outline: "rgb(var(--color-outline-rgb) / <alpha-value>)",
        "outline-variant": "rgb(var(--color-outline-variant-rgb) / <alpha-value>)",
        error: "rgb(var(--color-error-rgb) / <alpha-value>)",
        "error-container": "rgb(var(--color-error-container-rgb) / <alpha-value>)",
        "status-error": "rgb(var(--color-status-error-rgb) / <alpha-value>)",
        "status-warning": "rgb(var(--color-status-warning-rgb) / <alpha-value>)",
        "status-success": "rgb(var(--color-status-success-rgb) / <alpha-value>)",
        panel: "rgb(var(--color-panel-rgb) / <alpha-value>)",
      },
      fontFamily: {
        display: ["Manrope", "sans-serif"],
        body: ["Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "Consolas", "monospace"],
      },
    },
  },
  plugins: [],
};
